### PR TITLE
#144 meteor update

### PR DESCRIPTION
**Pull request by ya7ya**
This updates meteor to 1.5.2.2 + dependencies 
#144

### CODE REVIEW

**Comment by jellegerbrandy** [comment]
Hey many thanks, @ya7ya . 
The trouble is that the `meteor test` commands times out on `starting the app` in circleci on the command: `TEST_BROWSER_DRIVER=nightmare NODE_OPTIONS='--harmony' meteor test --settings settings-dev.json --once --driver-package dispatch:mocha  --port 9999`

For me, locally, the test just runs fine. Can you check on your machine if it works?

**Comment by ya7ya** [comment]
@jellegerbrandy I'm on it 👍 I'll check it out

**Comment by ya7ya** [comment]
@jellegerbrandy . This didn't timeout on my machine, but I'll check out why circle keeps timing out. I'll open a separate issue for this if it persist

**Comment by jellegerbrandy** [comment]
Yeah, very nasty to debug this. I am trying a stupid "rebuild without cache" now, perhaps that will work.

**Comment by jellegerbrandy** [comment]
https://blog.meteor.com/announcing-meteor-1-6-abf30f29e2c6

**Pull request merged**
